[build]
  entrypoint = ["./tmp/emly-api.exe"]
  cmd = "go build -o ./tmp/emly-api.exe ."
  include_ext = ["go", ".env", ".sql", ".tmpl"]
  exclude_dir = ["tmp", "vendor", "build", ".git", ".claude", ".idea", ".vscode"]
